import React, { StrictMode, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { createRoot } from 'react-dom/client';
import { createPortal } from 'react-dom';
import { BarChart3, BriefcaseBusiness, CalendarDays, Check, ChevronDown, FileText, FolderKanban, Globe2, Image as ImageIcon, LayoutDashboard, Link2, LogOut, Mail, Menu, MessageSquare, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Star, Tag, Trash2, UploadCloud, Users, X, Zap } from 'lucide-react';
import './styles.css';

type Section='dashboard'|'leads'|'projects'|'services'|'technologies'|'team'|'testimonials'|'blog'|'media'|'settings';
type Item=Record<string,any>;
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';
const nav:[Section,string,any][]=[['dashboard','Dashboard',LayoutDashboard],['leads','Leads',Mail],['projects','Projects',FolderKanban],['services','Services',BriefcaseBusiness],['technologies','Technologies',Zap],['team','Team',Users],['testimonials','Testimonials',MessageSquare],['blog','Blog',FileText],['media','Media',Tag],['settings','Settings',Settings]];

class ApiError extends Error{status:number;constructor(message:string,status=0){super(message);this.name='ApiError';this.status=status}}
async function api(path:string,options:RequestInit={}){
  const headers=new Headers(options.headers||{});
  if(options.body && !(options.body instanceof FormData)) headers.set('Content-Type','application/json');
  let res:Response;
  try{res=await fetch(`${API}${path}`,{...options,credentials:'include',headers});}
  catch{throw new ApiError(`Cannot connect to the DevStak API at ${API}. Start the server on port 4000 and try again.`)}
  const body=await res.json().catch(()=>({}));
  if(!res.ok) throw new ApiError(body.message||`Request failed (${res.status})`,res.status);
  return body;
}
function getSectionFromPath():Section{const parts=window.location.pathname.split('/').filter(Boolean);const candidate=parts[1] as Section|undefined;return candidate&&nav.some(x=>x[0]===candidate)?candidate:'dashboard'}

class ErrorBoundary extends React.Component<{children:ReactNode},{error:string|null}>{
  state={error:null as string|null};
  static getDerivedStateFromError(error:unknown){return {error:error instanceof Error?error.message:'Unexpected admin page error'}}
  render(){if(this.state.error)return <div className="content"><section className="panel"><h2>Something went wrong</h2><p>{this.state.error}</p><button className="primary" onClick={()=>this.setState({error:null})}>Try again <Zap/></button></section></div>;return this.props.children}
}

function App(){
 const sessionCheckStarted=useRef(false);
 const [user,setUser]=useState<Item|null>(null); const [checking,setChecking]=useState(true); const [apiError,setApiError]=useState(''); const [section,setSection]=useState<Section>(getSectionFromPath()); const [collapsed,setCollapsed]=useState(false); const [query,setQuery]=useState('');
 const checkSession=()=>{setChecking(true);setApiError('');api('/auth/me').then(x=>setUser(x.user)).catch((e)=>{if(e instanceof ApiError&&e.status===401)setUser(null);else setApiError(e instanceof Error?e.message:'Unable to connect to the API')}).finally(()=>setChecking(false))};
 useEffect(()=>{if(sessionCheckStarted.current)return;sessionCheckStarted.current=true;checkSession()},[]);
 useEffect(()=>{const onPop=()=>setSection(getSectionFromPath());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
 const navigate=(next:Section)=>{const path=next==='dashboard'?'/admin/':'/admin/'+next;window.history.pushState({},'',path);setSection(next);setQuery('')};
 if(checking)return <div className="loginPage"><div className="loginCard"><h2>Loading admin console…</h2></div></div>;
 if(apiError)return <div className="loginPage"><div className="loginCard"><div className="loginBrand"><div className="brandMark">DS</div><div><b>DEV<span>STAK</span></b><small>ADMIN CONSOLE</small></div></div><small className="loginEyebrow">API CONNECTION</small><h1>Backend unavailable.</h1><p>{apiError}</p><button className="loginButton" onClick={checkSession}>Retry connection <Zap/></button></div></div>;
 if(!user)return <Login onLogin={setUser}/>;
 const title=nav.find(x=>x[0]===section)?.[1]||'Dashboard';
 return <div className="admin"><aside className={collapsed?'collapsed':''}><div className="brand"><div className="brandMark">DS</div>{!collapsed&&<div><b>DEV<span>STAK</span></b><small>ADMIN CONSOLE</small></div>}</div><button className="collapse" onClick={()=>setCollapsed(v=>!v)}>{collapsed?<Menu/>:<X/>}</button><nav>{nav.map(([id,label,Icon])=><button key={id} className={section===id?'active':''} onClick={()=>navigate(id)}><Icon/>{!collapsed&&<span>{label}</span>}</button>)}</nav>{!collapsed&&<div className="sideBottom"><div className="secure"><ShieldCheck/><div><b>{user.name}</b><small>{user.role} · Private workspace</small></div></div><button onClick={async()=>{await api('/auth/logout',{method:'POST'});setUser(null)}}><LogOut/> Sign out</button></div>}</aside><main><header><div><small>DEVSTAK / ADMIN</small><h1>{title}</h1></div><div className="headerActions"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workspace..."/></div><button className="avatar">{user.name?.slice(0,2).toUpperCase()}</button></div></header><ErrorBoundary>{section==='dashboard'&&<Dashboard go={navigate}/>} {section==='projects'&&<Projects query={query}/>} {section==='leads'&&<Leads/>}{section==='services'&&<Services/>}{section==='technologies'&&<Technologies/>}{section==='team'&&<Team/>}{section==='testimonials'&&<Testimonials/>}{section==='blog'&&<Blog/>}{section==='media'&&<Media/>}{section==='settings'&&<SettingsPage/>}</ErrorBoundary></main></div>
}

function Login({onLogin}:{onLogin:(u:Item)=>void}){const [email,setEmail]=useState('admin@devstak.local');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const x=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(x.user)}catch(err){setError(err instanceof Error?err.message:'Unable to sign in')}finally{setLoading(false)}}return <div className="loginPage"><div className="loginGlow"/><div className="loginCard"><div className="loginBrand"><div className="brandMark">DS</div><div><b>DEV<span>STAK</span></b><small>ADMIN CONSOLE</small></div></div><small className="loginEyebrow">PRIVATE WORKSPACE</small><h1>Manage the system<br/><span>behind the brand.</span></h1><p>Projects, services, technology, testimonials, leads and site settings — all connected to the production API.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/></label>{error&&<div className="loginError">{error}</div>}<button className="loginButton" disabled={loading}>{loading?'Signing in…':'Sign in'} <Zap/></button></form></div></div>}

function Dashboard({go}:{go:(s:Section)=>void}){const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{api('/admin/dashboard').then(setData).catch(e=>setError(e.message))},[]);return <div className="content"><div className="welcome"><div><span>CONTENT CONTROL CENTER</span><h2>Run DevStak from one place.</h2><p>Changes saved here become API data for the public website.</p></div><button onClick={()=>go('projects')}>Manage projects <FolderKanban/></button></div>{error&&<div className="loginError">{error}</div>}<div className="stats"><Stat label="Projects" value={data?.stats.projects??'—'}/><Stat label="Open leads" value={data?.stats.unread??'—'}/><Stat label="Active services" value={data?.stats.services??'—'}/><Stat label="Technologies" value={data?.stats.technologies??'—'}/><Stat label="Team members" value={data?.stats.team??'—'}/></div><div className="grid3"><Panel title="Public website"><Health text="Dynamic content API connected"/><Health text="Published content only"/><Health text="Admin changes persist in PostgreSQL"/></Panel><Panel title="Quick actions"><Action text="Add project" onClick={()=>go('projects')} icon={<Plus/>}/><Action text="Edit services" onClick={()=>go('services')} icon={<BriefcaseBusiness/>}/><Action text="Update technology stack" onClick={()=>go('technologies')} icon={<Zap/>}/><Action text="Manage team" onClick={()=>go('team')} icon={<Users/>}/></Panel><Panel title="Architecture"><Health text="React + Vite frontend"/><Health text="Express + Prisma API"/><Health text="JWT + HttpOnly admin session"/></Panel></div></div>}
function Stat({label,value}:{label:string,value:string}){return <article className="stat"><div className="statIcon"><BarChart3/></div><small>{label}</small><b>{value}</b><span>Live database value</span></article>}
function Panel({title,children}:{title:string;children:ReactNode}){return <section className="panel"><div className="panelHead"><h3>{title}</h3></div>{children}</section>}
function Health({text}:{text:string}){return <div className="health"><span>✓</span><b>{text}</b></div>}
function Action({text,onClick,icon}:{text:string;onClick:()=>void;icon:ReactNode}){return <button className="action" onClick={onClick}>{icon}<span>{text}</span><ChevronDown/></button>}

function Projects({query}:{query:string}){
 const [items,setItems]=useState<Item[]>([]);
 const [editing,setEditing]=useState<Item|null>(null);
 const [techs,setTechs]=useState<Item[]>([]);
 const [error,setError]=useState('');
 const [loading,setLoading]=useState(true);
 const [pendingDelete,setPendingDelete]=useState<Item|null>(null);
 const [filter,setFilter]=useState<'ALL'|'PUBLISHED'|'DRAFT'|'FEATURED'>('ALL');
 const load=async()=>{setLoading(true);try{const [p,t]=await Promise.all([api('/admin/projects'),api('/admin/technologies')]);setItems(p.projects||[]);setTechs(t.technologies||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load projects')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async(data:Item)=>{try{const body={title:data.title,slug:data.slug,type:data.type,shortDescription:data.shortDescription,description:data.description,problem:data.problem||undefined,solution:data.solution||undefined,featured:!!data.featured,status:data.status||'DRAFT',coverImage:data.coverImage||undefined,liveUrl:data.liveUrl||undefined,githubUrl:data.githubUrl||undefined,galleryImages:data.galleryImages||[],highlights:data.highlights||[],technologyIds:data.technologyIds||[]};if(editing?.id)await api(`/admin/projects/${editing.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/admin/projects',{method:'POST',body:JSON.stringify(body)});setEditing(null);await load()}catch(e){setError(e instanceof ApiError&&e.status===409?e.message:e instanceof Error?e.message:'Unable to save project')}};
 const remove=async(id:string)=>{try{await api(`/admin/projects/${id}`,{method:'DELETE'});setPendingDelete(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete project')}};
 const beginAdd=()=>{const base='new-project';let slug=base;let i=2;while(items.some(p=>p.slug===slug)){slug=`${base}-${i++}`};setEditing({status:'DRAFT',featured:false,technologyIds:[],galleryImages:[],highlights:[],type:'Web Application',slug})};
 const visible=items.filter(p=>{const q=query.trim().toLowerCase();const matchesQuery=!q||`${p.title} ${p.type} ${p.shortDescription||''}`.toLowerCase().includes(q);if(!matchesQuery)return false;if(filter==='PUBLISHED')return String(p.status).toUpperCase()==='PUBLISHED';if(filter==='DRAFT')return String(p.status).toUpperCase()==='DRAFT';if(filter==='FEATURED')return !!p.featured;return true});
 const published=items.filter(p=>String(p.status).toUpperCase()==='PUBLISHED').length;
 const drafts=items.filter(p=>String(p.status).toUpperCase()==='DRAFT').length;
 const featured=items.filter(p=>!!p.featured).length;
 return <div className="content projectAdmin">
   <div className="projectsHeader"><div><span className="pageEyebrow">PORTFOLIO CMS</span><h2>Projects</h2><p>Manage the case studies and work displayed across the public DevStak website.</p></div><button className="projectAddButton" onClick={beginAdd}><Plus/> Add project</button></div>
   {error&&<div className="loginError">{error}</div>}
   <div className="projectStats"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}><b>{items.length}</b><span>Total projects</span><i><FolderKanban/></i></button><button className={filter==='PUBLISHED'?'active':''} onClick={()=>setFilter('PUBLISHED')}><b>{published}</b><span>Published</span><i className="green"><Check/></i></button><button className={filter==='FEATURED'?'active':''} onClick={()=>setFilter('FEATURED')}><b>{featured}</b><span>Featured</span><i className="gold"><Star/></i></button><button className={filter==='DRAFT'?'active':''} onClick={()=>setFilter('DRAFT')}><b>{drafts}</b><span>Drafts</span><i className="gray"><FileText/></i></button></div>
   <div className="projectToolbar"><div className="projectFilters"><button className={filter==='ALL'?'selected':''} onClick={()=>setFilter('ALL')}>All <span>{items.length}</span></button><button className={filter==='PUBLISHED'?'selected':''} onClick={()=>setFilter('PUBLISHED')}>Published <span>{published}</span></button><button className={filter==='FEATURED'?'selected':''} onClick={()=>setFilter('FEATURED')}>Featured <span>{featured}</span></button><button className={filter==='DRAFT'?'selected':''} onClick={()=>setFilter('DRAFT')}>Drafts <span>{drafts}</span></button></div><div className="projectResult"><Search/><span>{visible.length} {visible.length===1?'project':'projects'}</span></div></div>
   {loading?<div className="loadingPanel"><div className="loadingOrb"><FolderKanban/></div><b>Loading projects</b><span>Syncing with the DevStak API…</span></div>:<>
     {visible.length?<div className="projectCards">{visible.map(p=>{const techNames=(p.technologies||[]).map((x:any)=>x.technology?.name).filter(Boolean);return <article className="projectAdminCard" key={p.id}>
       <div className="projectCover">{p.coverImage?<img src={p.coverImage} alt=""/>:<div className="projectCoverFallback"><FolderKanban/></div>}<div className="projectCoverShade"/><span className="projectType">{p.type||'Web Application'}</span><button className="projectMenu" onClick={()=>setEditing({...p,technologyIds:p.technologies?.map((x:any)=>x.technology.id)||[],galleryImages:p.galleryImages||[],highlights:p.highlights||[]})} title="Edit project"><MoreHorizontal/></button>{p.featured&&<span className="featuredProject"><Star/> Featured</span>}</div>
       <div className="projectCardBody"><div className="projectCardTitle"><div><h3>{p.title}</h3><p>{p.shortDescription||'No short description added yet.'}</p></div><span className={'status '+String(p.status||'DRAFT').toLowerCase()}>{p.status||'DRAFT'}</span></div>
       <div className="projectTechs">{techNames.slice(0,5).map((name:string)=><span key={name}>{name}</span>)}{techNames.length>5&&<span>+{techNames.length-5}</span>}{!techNames.length&&<span>No technologies assigned</span>}</div>
       <div className="projectCardFooter"><div className="projectLinks"><span>{p.galleryImages?.length||0} gallery images</span><span>{p.highlights?.length||0} highlights</span></div><div className="projectActions"><button onClick={()=>setEditing({...p,technologyIds:p.technologies?.map((x:any)=>x.technology.id)||[],galleryImages:p.galleryImages||[],highlights:p.highlights||[]})}><MoreHorizontal/> Edit</button><button className="deleteProjectButton" onClick={()=>setPendingDelete(p)}><Trash2/></button></div></div></div>
     </article>})}</div>:<div className="projectEmpty"><div><FolderKanban/></div><b>No projects found</b><span>{items.length?'Try another filter or search term.':'Click “Add project” to create your first case study.'}</span>{!items.length&&<button className="primary" onClick={beginAdd}><Plus/> Add project</button>}</div>}
   </>}
   {editing&&<ProjectForm item={editing} techs={techs} existingSlugs={items.filter(p=>p.id!==editing.id).map(p=>p.slug)} close={()=>setEditing(null)} save={save}/>} {pendingDelete&&<ConfirmDialog title="Delete this project?" description={`Are you sure you want to permanently delete “${pendingDelete.title}”? This will remove the project from the portfolio and admin database. This action cannot be undone.`} confirmLabel="Delete project" onCancel={()=>setPendingDelete(null)} onConfirm={()=>remove(pendingDelete.id)}/>}</div>
}
function ProjectForm({item,techs,existingSlugs,close,save}:{item:Item;techs:Item[];existingSlugs:string[];close:()=>void;save:(x:Item)=>void}){
 const [v,setV]=useState(item);
 const set=(key:string,value:any)=>setV(prev=>({...prev,[key]:value}));
 const slugify=(text:string)=>text.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
 return <Modal title={item.id?'Edit project':'Create a new project'} eyebrow="PROJECT STUDIO" close={close}>
   <div className="formIntro"><div className="formIcon"><FolderKanban/></div><div><b>{item.id?'Update your case study':'Build a portfolio case study'}</b><span>Everything saved here can appear on the public DevStak website.</span></div></div>
   <FormSection title="Identity" hint="The information visitors see first.">
     <div className="formGrid twoCols">
       <Field label="Project title" required><input autoFocus value={v.title||''} onChange={e=>{const title=e.target.value;setV(prev=>{const generated=slugify(title);const current=prev.slug||'';const shouldGenerate=!item.id||!current||current===slugify(prev.title||'');let next=shouldGenerate?generated:current;if(shouldGenerate&&existingSlugs.includes(next)){let i=2;while(existingSlugs.includes(`${generated}-${i}`))i++;next=`${generated}-${i}`;}return {...prev,title,slug:next}})}} placeholder="e.g. CoupleNest"/></Field>
       <Field label="URL slug" required hint="Used in /projects/your-slug"><input value={v.slug||''} onChange={e=>set('slug',slugify(e.target.value))} placeholder="couplenest"/></Field>
     </div>
     <div className="formGrid twoCols">
       <Field label="Project type" required><input value={v.type||''} onChange={e=>set('type',e.target.value)} placeholder="Web Application"/></Field>
       <Field label="Short description" required><input value={v.shortDescription||''} onChange={e=>set('shortDescription',e.target.value)} placeholder="One clear sentence"/></Field>
     </div>
   </FormSection>
   <FormSection title="Case study" hint="Tell the story behind the project.">
     <Field label="Description" required><textarea className="largeTextarea" value={v.description||''} onChange={e=>set('description',e.target.value)} placeholder="Explain what was built, who it serves and the key experience..."/></Field>
     <div className="formGrid twoCols">
       <Field label="Problem"><textarea value={v.problem||''} onChange={e=>set('problem',e.target.value)} placeholder="What problem did this solve?"/></Field>
       <Field label="Solution"><textarea value={v.solution||''} onChange={e=>set('solution',e.target.value)} placeholder="How did you solve it?"/></Field>
     </div>
   </FormSection>
   <FormSection title="Visual & links" hint="Use Cloudinary for polished project imagery.">
     <ImageField label="Cover image" value={v.coverImage||''} onChange={url=>set('coverImage',url)}/>
     <div className="formGrid twoCols">
       <Field label="Live website"><div className="inputWithIcon"><Link2/><input value={v.liveUrl||''} onChange={e=>set('liveUrl',e.target.value)} placeholder="https://..."/></div></Field>
       <Field label="GitHub repository"><div className="inputWithIcon"><Globe2/><input value={v.githubUrl||''} onChange={e=>set('githubUrl',e.target.value)} placeholder="https://github.com/..."/></div></Field>
     </div>
   </FormSection>
   <FormSection title="Case study highlights" hint="Add short capability or outcome labels shown on the project page.">
     <TagEditor value={v.highlights||[]} onChange={value=>set('highlights',value)} placeholder="e.g. Real-time analytics"/>
   </FormSection>
   <FormSection title="Project gallery" hint="Add additional Cloudinary screenshots. They appear in the case study gallery.">
     <GalleryField value={v.galleryImages||[]} onChange={value=>set('galleryImages',value)}/>
   </FormSection>
   <FormSection title="Publishing" hint="Control visibility and presentation.">
     <div className="formGrid twoCols">
       <Field label="Status"><select value={v.status||'DRAFT'} onChange={e=>set('status',e.target.value)}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></Field>
       <Field label="Technologies"><select className="techSelect" multiple value={v.technologyIds||[]} onChange={e=>set('technologyIds',Array.from(e.target.selectedOptions).map(o=>o.value))}>{techs.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><span className="fieldHint">Hold Ctrl/Cmd to select multiple technologies.</span></Field>
     </div>
     <Switch label="Feature this project" checked={!!v.featured} onChange={checked=>set('featured',checked)} description="Show it in highlighted portfolio sections."/>
   </FormSection>
   <FormActions close={close} label={item.id?'Save project':'Create project'}/>
   <button type="button" className="hiddenSave" onClick={()=>save(v)} aria-hidden="true">save</button>
 </Modal>
}

function ImageField({label,value,onChange}:{label:string;value:string;onChange:(url:string)=>void}){
 const [uploading,setUploading]=useState(false); const [drag,setDrag]=useState(false);
 const upload=async(file:File)=>{if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}setUploading(true);try{const form=new FormData();form.append('file',file);const body=await api('/admin/media/upload',{method:'POST',body:form});onChange(body.media.url)}catch(e){alert(e instanceof Error?e.message:'Upload failed')}finally{setUploading(false)}};
 return <Field label={label} hint="Recommended: landscape image, optimized before upload.">
   <div className={'uploadZone '+(drag?'dragging':'')+(value?' hasPreview':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files?.[0];if(f)upload(f)}}>
     {value?<><img src={value} className="uploadPreview" alt="Project preview"/><div className="uploadOverlay"><label className="uploadButton"><UploadCloud/> Replace image<input hidden type="file" accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label><button type="button" className="ghostButton" onClick={()=>onChange('')}>Remove</button></div></>:<><div className="uploadIcon"><ImageIcon/></div><b>{uploading?'Uploading to Cloudinary…':'Drop an image here'}</b><span>or click to browse • PNG, JPG, WEBP up to 10MB</span><label className="uploadButton"><UploadCloud/> Choose image<input hidden type="file" accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label></>}
   </div>
   <div className="urlRow"><Link2/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Or paste a Cloudinary image URL"/></div>
 </Field>
}

function TagEditor({value,onChange,placeholder}:{value:string[];onChange:(value:string[])=>void;placeholder:string}){
 const [draft,setDraft]=useState('');
 const add=()=>{const next=draft.trim();if(!next)return;if(!value.includes(next))onChange([...value,next]);setDraft('')};
 return <div className="tagEditor"><div className="tagEditorInput"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}} placeholder={placeholder}/><button type="button" onClick={add}><Plus/> Add</button></div><div className="tagList">{value.map(tag=><span key={tag}>{tag}<button type="button" onClick={()=>onChange(value.filter(x=>x!==tag))}><X/></button></span>)}{!value.length&&<small>No highlights added yet.</small>}</div></div>}

function GalleryField({value,onChange}:{value:string[];onChange:(value:string[])=>void}){
 const [uploading,setUploading]=useState(false);
 const upload=async(file:File)=>{if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}setUploading(true);try{const form=new FormData();form.append('file',file);const body=await api('/admin/media/upload',{method:'POST',body:form});onChange([...value,body.media.url])}catch(e){alert(e instanceof Error?e.message:'Upload failed')}finally{setUploading(false)}};
 return <div className="galleryField"><div className="galleryGrid">{value.map((url,i)=><div className="galleryItem" key={url+i}><img src={url} alt={`Gallery ${i+1}`}/><button type="button" onClick={()=>onChange(value.filter((_,n)=>n!==i))}><X/></button></div>)}<label className="galleryAdd"><UploadCloud/><b>{uploading?'Uploading…':'Add screenshot'}</b><span>PNG, JPG, WEBP</span><input hidden type="file" accept="image/*" disabled={uploading} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/></label></div><div className="urlRow"><Link2/><input placeholder="Paste a Cloudinary URL and press Enter" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();const u=e.currentTarget.value.trim();if(u&&!value.includes(u))onChange([...value,u]);e.currentTarget.value=''}}}/></div></div>}

function FormSection({title,hint,children}:{title:string;hint:string;children:ReactNode}){return <section className="formSection"><div className="formSectionHead"><div><h3>{title}</h3><p>{hint}</p></div><span/></div>{children}</section>}
function Switch({label,checked,onChange,description}:{label:string;checked:boolean;onChange:(v:boolean)=>void;description?:string}){return <button type="button" className={'switchRow '+(checked?'on':'')} onClick={()=>onChange(!checked)}><span className="switchCopy"><b>{label}</b>{description&&<small>{description}</small>}</span><span className="switch"><i/></span></button>}
function FormActions({close,label}:{close:()=>void;label:string}){return <div className="modalActions stickyActions"><button type="button" onClick={close}>Cancel</button><button type="button" className="primary" onClick={()=>document.querySelector<HTMLButtonElement>('.modal .hiddenSave')?.click()}><Check/> {label}</button></div>}

function Services(){return <ResourcePage title="Services" endpoint="services" description="Create and manage the services displayed on the public DevStak website." fields={['title','slug','description','iconKey']} defaults={{published:true,sortOrder:0,iconKey:'Layers3'}} extra={(v,setV)=><><Field label="Display order" hint="Lower numbers appear first."><input type="number" min="0" value={v.sortOrder??0} onChange={e=>setV({...v,sortOrder:Number(e.target.value)})}/></Field><Switch label="Published" checked={v.published??true} onChange={checked=>setV({...v,published:checked})} description="Visible on the public Services page."/></>}/>} 
function Technologies(){return <ResourcePage title="Technology Stack" endpoint="technologies" description="Manage technologies shown across the public website and project case studies." fields={['name','slug','category','iconKey','websiteUrl']} defaults={{featured:true,sortOrder:0,iconKey:'Code2',category:'Backend'}} extra={(v,setV)=><><Field label="Display order"><input type="number" min="0" value={v.sortOrder??0} onChange={e=>setV({...v,sortOrder:Number(e.target.value)})}/></Field><Switch label="Featured technology" checked={v.featured??true} onChange={checked=>setV({...v,featured:checked})} description="Include in highlighted technology sections."/></>}/>} 

function Team(){
 const [items,setItems]=useState<Item[]>([]); const [editing,setEditing]=useState<Item|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [pendingDelete,setPendingDelete]=useState<Item|null>(null);
 const load=async()=>{setLoading(true);try{const x=await api('/admin/team');setItems(x.team||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load team')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const save=async(v:Item)=>{try{const body={name:v.name,role:v.role,bio:v.bio||undefined,photoUrl:v.photoUrl||undefined,linkedinUrl:v.linkedinUrl||undefined,githubUrl:v.githubUrl||undefined,websiteUrl:v.websiteUrl||undefined,featured:!!v.featured,sortOrder:Number(v.sortOrder??0)};if(v.id)await api(`/admin/team/${v.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/admin/team',{method:'POST',body:JSON.stringify(body)});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save team member')}};
 const remove=async(id:string)=>{try{await api(`/admin/team/${id}`,{method:'DELETE'});setPendingDelete(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete team member')}};
 return <div className="content"><Toolbar text="Manage the people showcased on the public DevStak website. Only featured members are visible publicly." button="Add team member" onClick={()=>setEditing({name:'',role:'',bio:'',photoUrl:'',linkedinUrl:'',githubUrl:'',websiteUrl:'',featured:true,sortOrder:items.length})}/>{error&&<div className="loginError">{error}</div>}{loading?<div className="loadingPanel"><div className="loadingOrb"><Users/></div><b>Loading team</b><span>Syncing with the DevStak API…</span></div>:<div className="cards teamCards">{items.map(x=><article className="contentCard teamCard" key={x.id}>{x.photoUrl?<img className="teamAdminAvatar" src={x.photoUrl} alt=""/>:<div className="teamAdminAvatar teamFallback">{String(x.name||'TM').split(' ').map((n:string)=>n[0]).slice(0,2).join('').toUpperCase()}</div>}<div className="resourceBody"><div className="resourceMeta"><small>TEAM MEMBER</small><span className={x.featured?'featuredBadge':'hiddenBadge'}>{x.featured?'FEATURED':'HIDDEN'}</span></div><h3>{x.name}</h3><p>{x.role}</p><div className="resourceFooter"><span>Order {x.sortOrder??0}</span><span>{x.bio?'Bio added':'No bio yet'}</span></div></div><div className="cardActions"><button onClick={()=>setEditing({...x})} title="Edit"><MoreHorizontal/></button><button className="danger" onClick={()=>setPendingDelete(x)} title="Delete"><Trash2/></button></div></article>)}{!items.length&&<div className="emptyState"><div><Users/></div><b>No team members yet</b><span>Add the people you want visitors to see on the website.</span><button className="primary" onClick={()=>setEditing({name:'',role:'',bio:'',photoUrl:'',linkedinUrl:'',githubUrl:'',websiteUrl:'',featured:true,sortOrder:0})}><Plus/> Add team member</button></div>}</div>}{editing&&<TeamForm value={editing} close={()=>setEditing(null)} save={save}/>} {pendingDelete&&<ConfirmDialog title="Delete this team member?" description={`This will permanently remove “${pendingDelete.name}” from the team directory.`} confirmLabel="Delete member" onCancel={()=>setPendingDelete(null)} onConfirm={()=>remove(pendingDelete.id)}/>}</div>
}
function TeamForm({value,close,save}:{value:Item;close:()=>void;save:(v:Item)=>void}){const [v,setV]=useState(value);const set=(key:string,val:any)=>setV(prev=>({...prev,[key]:val}));return <Modal title={value.id?'Edit team member':'Add team member'} eyebrow="TEAM DIRECTORY" close={close}><div className="formIntro"><div className="formIcon"><Users/></div><div><b>{value.id?'Update this profile':'Create a public team profile'}</b><span>Only members marked as featured will appear on the public website.</span></div></div><FormSection title="Profile" hint="Introduce the person clearly and professionally."><div className="formGrid twoCols"><Field label="Full name" required><input autoFocus value={v.name||''} onChange={e=>set('name',e.target.value)} placeholder="Aftab Mumtaz"/></Field><Field label="Role / position" required><input value={v.role||''} onChange={e=>set('role',e.target.value)} placeholder="Founder & Full-Stack Developer"/></Field></div><Field label="Bio"><textarea className="largeTextarea" value={v.bio||''} onChange={e=>set('bio',e.target.value)} placeholder="A short introduction visitors can read on the team page."/></Field></FormSection><FormSection title="Profile image" hint="Upload through Cloudinary or paste a hosted image URL."><ImageField label="Team photo" value={v.photoUrl||''} onChange={url=>set('photoUrl',url)}/></FormSection><FormSection title="Professional links" hint="Optional links shown on the public team card."><div className="formGrid twoCols"><Field label="LinkedIn URL"><input value={v.linkedinUrl||''} onChange={e=>set('linkedinUrl',e.target.value)} placeholder="https://linkedin.com/in/..."/></Field><Field label="GitHub URL"><input value={v.githubUrl||''} onChange={e=>set('githubUrl',e.target.value)} placeholder="https://github.com/..."/></Field><Field label="Website URL"><input value={v.websiteUrl||''} onChange={e=>set('websiteUrl',e.target.value)} placeholder="https://..."/></Field><Field label="Display order" hint="Lower numbers appear first."><input type="number" min="0" value={v.sortOrder??0} onChange={e=>set('sortOrder',Number(e.target.value))}/></Field></div></FormSection><FormSection title="Visibility" hint="Choose whether this person is showcased publicly."><Switch label="Feature on website" checked={v.featured!==false} onChange={checked=>set('featured',checked)} description="Featured members appear on the public Team section."/></FormSection><div className="modalActions stickyActions"><button type="button" onClick={close}>Cancel</button><button type="button" className="primary" onClick={()=>save(v)}><Check/> {value.id?'Save member':'Add member'}</button></div></Modal>}

function Testimonials(){return <ResourcePage title="Testimonials" endpoint="testimonials" description="Manage client testimonials and publish them when ready." fields={['client','company','role','content','rating']} defaults={{status:'DRAFT',rating:5}} image="photoUrl"/>}
function Blog(){return <ResourcePage title="Blog & Content" endpoint="blog" description="Create articles and publish them through the public DevStak website." fields={['title','slug','excerpt','content']} defaults={{status:'DRAFT'}} image="coverImage"/>}

function ResourcePage({title,endpoint,description,fields,defaults,extra,image}:{title:string;endpoint:string;description:string;fields:string[];defaults:Item;extra?:(v:Item,setV:(v:Item)=>void)=>ReactNode;image?:string}){
 const [items,setItems]=useState<Item[]>([]);const [projects,setProjects]=useState<Item[]>([]);const [editing,setEditing]=useState<Item|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const requests:[Promise<any>,Promise<any>|null]=[api(`/admin/${endpoint}`),endpoint==='testimonials'?api('/admin/projects'):null];const [x,p]=await Promise.all(requests);setItems(x[endpoint==='blog'?'posts':endpoint]||[]);if(p)setProjects(p.projects||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load data')}finally{setLoading(false)}};
 useEffect(()=>{load()},[endpoint]);
 const save=async(v:Item)=>{try{const body={...v};delete body.id;delete body.createdAt;delete body.updatedAt;delete body.project;delete body.notes;if(endpoint==='testimonials'&&body.projectId==='')body.projectId=null;if(endpoint==='blog'&&body.publishedAt==='')body.publishedAt=null;if(v.id)await api(`/admin/${endpoint}/${v.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api(`/admin/${endpoint}`,{method:'POST',body:JSON.stringify(body)});setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save record')}};
 const del=async(id:string)=>{if(!confirm(`Delete this ${title.toLowerCase()} record?`))return;try{await api(`/admin/${endpoint}/${id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete record')}};
 const add=()=>setEditing({...defaults,sortOrder:defaults.sortOrder??items.length});
 const addLabel=title==='Technology Stack'?'technology':title==='Blog & Content'?'post':title.endsWith('s')?title.slice(0,-1):title;
 return <div className="content"><Toolbar text={description} button={`Add ${addLabel}`} onClick={add}/>{error&&<div className="loginError">{error}</div>}{loading?<div className="loadingPanel"><div className="loadingOrb"><Zap/></div><b>Loading {title.toLowerCase()}</b><span>Syncing with the DevStak API…</span></div>:<div className="cards resourceCards">{items.map(x=><article className="contentCard resourceCard" key={x.id}>{image&&x[image]?<img className="resourceImage" src={x[image]} alt=""/>:<div className="contentIcon"><Zap/></div>}<div className="resourceBody"><div className="resourceMeta"><small>{x.status||x.category||title.toUpperCase()}</small>{x.rating&&<span className="rating"><Star/> {x.rating}</span>}</div><h3>{x.title||x.name||x.client}</h3><p>{x.description||x.content||x.excerpt||x.role||'Editable database content'}</p><div className="resourceFooter"><span>{endpoint==='services'?(x.published?'Published':'Hidden'):endpoint==='technologies'?(x.featured?'Featured':'Standard'):endpoint==='testimonials'?(x.company||'Client testimonial'):x.slug||'Content record'}</span></div></div><div className="cardActions"><button onClick={()=>setEditing({...x})} title="Edit"><MoreHorizontal/></button><button className="danger" onClick={()=>del(x.id)} title="Delete"><Trash2/></button></div></article>)}{!items.length&&<div className="emptyState"><div><Zap/></div><b>No {title.toLowerCase()} yet</b><span>Start building your content library by creating the first record.</span><button className="primary" onClick={add}><Plus/> Add {addLabel}</button></div>}</div>}{editing&&<ResourceForm title={title} fields={fields} value={editing} close={()=>setEditing(null)} save={save} extra={extra} image={image} projects={projects}/>}</div>
}

function ResourceForm({title,fields,value,close,save,extra,image,projects=[]}:{title:string;fields:string[];value:Item;close:()=>void;save:(v:Item)=>void;extra?:(v:Item,setV:(v:Item)=>void)=>ReactNode;image?:string;projects?:Item[]}){
 const [v,setV]=useState(value); const set=(key:string,val:any)=>setV(prev=>({...prev,[key]:val}));
 const slugify=(text:string)=>text.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
 const labels:Record<string,string>={title:'Title',slug:'URL slug',description:'Description',iconKey:'Icon key',name:'Technology name',category:'Category',websiteUrl:'Website URL',client:'Client name',company:'Company',role:'Role / position',content:'Testimonial',rating:'Rating',excerpt:'Excerpt'};
 const isBlog=title==='Blog & Content';
 return <Modal title={value.id?`Edit ${title}`:`Add ${title}`} eyebrow={isBlog?'EDITOR STUDIO':'CONTENT MANAGEMENT'} close={close}>
   <div className="formIntro"><div className="formIcon">{isBlog?<FileText/>:<Tag/>}</div><div><b>{value.id?'Refine this content':'Create polished content'}</b><span>Use concise copy and preview the result before publishing.</span></div></div>
   <FormSection title="Core information" hint="Keep names, slugs and descriptions clear and consistent.">
     <div className="formGrid twoCols">{fields.filter(f=>['title','name','client','company','role','category','iconKey'].includes(f)).map(f=><Field key={f} label={labels[f]||f} required={['title','name','client'].includes(f)}><input value={v[f]??''} onChange={e=>set(f,e.target.value)} placeholder={f==='iconKey'?'Lucide icon name':''}/></Field>)}</div>
     {fields.includes('slug')&&<Field label="URL slug" required hint="Lowercase, hyphenated and unique."><input value={v.slug||''} onChange={e=>set('slug',slugify(e.target.value))} placeholder="your-content-slug"/></Field>}
     {fields.includes('description')&&<Field label="Description" required><textarea value={v.description||''} onChange={e=>set('description',e.target.value)} placeholder="Describe this item for visitors..."/></Field>}
     {fields.includes('excerpt')&&<Field label="Excerpt" required><textarea value={v.excerpt||''} onChange={e=>set('excerpt',e.target.value)} placeholder="Short preview shown in article cards..."/></Field>}
     {fields.includes('content')&&<Field label={title==='Testimonials'?'Testimonial':'Article content'} required><textarea className="largeTextarea" value={v.content||''} onChange={e=>set('content',e.target.value)} placeholder={title==='Testimonials'?'What did the client say?':'Write the full article content...'}/></Field>}
   </FormSection>
   {image&&<FormSection title="Media" hint="Use Cloudinary to upload a clean, optimized image."><ImageField label={title==='Blog & Content'?'Cover image':'Client photo'} value={v[image]||''} onChange={url=>set(image,url)}/></FormSection>}
   {title==='Testimonials'&&<FormSection title="Proof & context" hint="Add credibility and connect the testimonial to a project."><div className="formGrid twoCols"><Field label="Rating"><div className="ratingInput">{[1,2,3,4,5].map(n=><button key={n} type="button" className={n<=(v.rating||0)?'selected':''} onClick={()=>set('rating',n)}><Star/></button>)}</div></Field><Field label="Related project"><select value={v.projectId||''} onChange={e=>set('projectId',e.target.value||null)}><option value="">No project linked</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></Field></div></FormSection>}
   {title==='Blog & Content'&&<FormSection title="Publishing" hint="Choose when this article becomes visible."><div className="formGrid twoCols"><Field label="Status"><select value={v.status||'DRAFT'} onChange={e=>set('status',e.target.value)}><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option><option value="ARCHIVED">Archived</option></select></Field><Field label="Publish date"><input type="datetime-local" value={v.publishedAt?new Date(v.publishedAt).toISOString().slice(0,16):''} onChange={e=>set('publishedAt',e.target.value?new Date(e.target.value).toISOString():null)}/></Field></div></FormSection>}
   {extra&&<FormSection title="Display settings" hint="Control how this item appears across the website.">{extra(v,setV)}</FormSection>}
   {title!=='Services'&&title!=='Technology Stack'&&title!=='Blog & Content'&&title!=='Testimonials'&&<Field label="Status"><select value={v.status||'DRAFT'} onChange={e=>set('status',e.target.value)}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></Field>}
   <div className="modalActions stickyActions"><button type="button" onClick={close}>Cancel</button><button type="button" className="primary" onClick={()=>save(v)}><Check/> {value.id?'Save changes':'Create record'}</button></div>
 </Modal>
}

function Leads(){const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=async()=>{setLoading(true);try{const x=await api('/admin/leads');setItems(x.leads||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load leads')}finally{setLoading(false)}};useEffect(()=>{load()},[]);const setStatus=async(id:string,status:string)=>{try{await api(`/admin/leads/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update lead')}};return <div className="content"><Toolbar text="Manage inquiries submitted from the public DevStak contact form." button="Refresh leads" onClick={load}/>{error&&<div className="loginError">{error}</div>}{loading?<p className="adminHint">Loading leads…</p>:<div className="table"><div className="thead"><span>Lead</span><span>Project</span><span>Budget</span><span>Status</span><span>Received</span><span/></div>{items.map(l=><div className="tr" key={l.id}><div className="projectCell"><div className="projectThumb">{String(l.name||'??').slice(0,2).toUpperCase()}</div><div><b>{l.name}</b><small>{l.email}{l.company?` · ${l.company}`:''}</small></div></div><span>{l.projectType}</span><span>{l.budget||'—'}</span><select value={l.status} onChange={e=>setStatus(l.id,e.target.value)}><option>NEW</option><option>CONTACTED</option><option>DISCOVERY</option><option>PROPOSAL_SENT</option><option>WON</option><option>LOST</option></select><span>{new Date(l.createdAt).toLocaleString()}</span><button className="more" title={l.message}><MessageSquare/></button></div>)}{!items.length&&<p className="adminHint">No leads received yet.</p>}</div>}</div>}

function Media(){const [items,setItems]=useState<Item[]>([]);const [uploading,setUploading]=useState(false);const load=()=>api('/admin/media').then(x=>setItems(x.media||[])).catch(()=>setItems([]));useEffect(()=>{load()},[]);const upload=async(file:File)=>{setUploading(true);try{const form=new FormData();form.append('file',file);await api('/admin/media/upload',{method:'POST',body:form});await load()}catch(e){alert(e instanceof Error?e.message:'Upload failed')}finally{setUploading(false)}};const del=async(id:string)=>{if(confirm('Delete this image from Cloudinary and the media library?')){await api(`/admin/media/${id}`,{method:'DELETE'});load()}};return <div className="content"><Toolbar text="Upload images to Cloudinary and reuse them across projects, blog posts and testimonials." button={uploading?'Uploading…':'Upload image'} onClick={()=>document.getElementById('mediaUploadInput')?.click()}/><input id="mediaUploadInput" hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=''}}/><div className="cards">{items.map(m=><article className="contentCard" key={m.id}><img src={m.url} alt={m.altText||m.filename} style={{width:96,height:72,objectFit:'cover',borderRadius:12}}/><div><small>Cloudinary</small><h3>{m.filename}</h3><p>{m.url}</p></div><button onClick={()=>navigator.clipboard?.writeText(m.url)}>Copy URL</button><button onClick={()=>del(m.id)}><X/></button></article>)}</div>{!items.length&&<p className="adminHint">No media uploaded yet.</p>}</div>}
function SettingsPage(){const [settings,setSettings]=useState<Item>({});const [keys]=useState(['brand.name','brand.tagline','contact.email','social.github','social.linkedin']);useEffect(()=>{api('/admin/settings').then(x=>setSettings(Object.fromEntries((x.settings||[]).map((s:any)=>[s.key,s.value])))).catch(()=>{})},[]);const save=async(key:string)=>{await api(`/admin/settings/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value:settings[key]||''})})};return <div className="content"><div className="settingsGrid"><Panel title="Public website settings">{keys.map(k=><label key={k}>{k}<input value={settings[k]||''} onChange={e=>setSettings({...settings,[k]:e.target.value})} onBlur={()=>save(k)}/></label>)}<p>Values are saved to SiteSetting and exposed by the public API.</p></Panel><Panel title="Security"><Health text="JWT + HttpOnly cookie authentication"/><Health text="Protected admin API routes"/><Health text="Owner / Admin roles in Prisma"/></Panel></div></div>}


function ConfirmDialog({title,description,confirmLabel='Delete',onCancel,onConfirm}:{title:string;description:string;confirmLabel?:string;onCancel:()=>void;onConfirm:()=>void}){const [busy,setBusy]=useState(false);useEffect(()=>{const previous=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)onCancel()};document.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',onKey)}},[busy,onCancel]);const dialog=<div className="confirmBack" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onCancel()}}><div className="confirmDialog" onMouseDown={e=>e.stopPropagation()}><div className="confirmIcon"><Trash2/></div><div className="confirmCopy"><span>CONFIRM ACTION</span><h2 id="confirm-title">{title}</h2><p>{description}</p></div><div className="confirmActions"><button type="button" onClick={onCancel} disabled={busy}>Cancel</button><button type="button" className="confirmDanger" disabled={busy} onClick={async()=>{setBusy(true);try{await onConfirm()}finally{setBusy(false)}}}>{busy?'Deleting…':confirmLabel}<Trash2/></button></div></div></div>;return createPortal(dialog,document.body)}

function Toolbar({text,button,onClick}:{text:string;button:string;onClick:()=>void}){return <div className="toolbar"><p>{text}</p><button className="primary" onClick={onClick}><Plus/> {button}</button></div>}
function Modal({title,eyebrow='CONTENT MANAGEMENT',close,children}:{title:string;eyebrow?:string;close:()=>void;children:ReactNode}){return <div className="modalBack" role="dialog" aria-modal="true"><div className="modal"><div className="modalTopline"><span>{eyebrow}</span><button className="close" onClick={close} aria-label="Close"><X/></button></div><h2>{title}</h2><div className="modalScroll">{children}</div></div></div>}
function Field({label,children,hint,required}:{label:string;children:ReactNode;hint?:string;required?:boolean}){return <label className="field"><span className="fieldLabel">{label}{required&&<i>*</i>}</span>{children}{hint&&<span className="fieldHint">{hint}</span>}</label>}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
